import { createHash } from "node:crypto";
import { type ChildProcess, spawn } from "node:child_process";
import {
  access,
  mkdir,
  readFile,
  readdir,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { createLogger } from "@openstreamgrid/common";

const DEFAULT_HASH_INTERVAL_MS = 250;
const STOP_TIMEOUT_MS = 5_000;
const DEFAULT_SEGMENT_DURATION_SECONDS = 2;
const DEFAULT_PLAYLIST_SIZE = 8;
const TEST_PATTERN_FRAME_RATE = 30;
const TEST_AUDIO_FREQUENCY_HZ = 1_000;
const AUDIO_SAMPLE_RATE_HZ = 48_000;
const HLS_DELETE_THRESHOLD = 2;
const logger = createLogger("origin");

/** Quality level definitions for Adaptive Bitrate streaming. */
export interface QualityLevel {
  /** Name used as subdirectory and variant key (low, med, high). */
  name: string;
  /** Output video width in pixels. */
  width: number;
  /** Output video height in pixels. */
  height: number;
  /** Target video bitrate (e.g. "500k"). */
  videoBitrate: string;
  /** Max video bitrate (same as target for CBR-like behavior). */
  maxrate: string;
  /** Buffer size (typically 2× videoBitrate). */
  bufsize: string;
  /** Audio bitrate (e.g. "64k" or "128k"). */
  audioBitrate: string;
}

/** Default adaptive-bitrate renditions generated by the origin. */
export const QUALITY_LEVELS: QualityLevel[] = [
  {
    name: "low",
    width: 640,
    height: 360,
    videoBitrate: "500k",
    maxrate: "500k",
    bufsize: "1000k",
    audioBitrate: "64k",
  },
  {
    name: "med",
    width: 854,
    height: 480,
    videoBitrate: "1500k",
    maxrate: "1500k",
    bufsize: "3000k",
    audioBitrate: "128k",
  },
  {
    name: "high",
    width: 1280,
    height: 720,
    videoBitrate: "3000k",
    maxrate: "3000k",
    bufsize: "6000k",
    audioBitrate: "128k",
  },
] as const;

/** Runtime configuration for the HLS stream generator. */
export interface StreamerOptions {
  outputDirectory: string;
  ffmpegPath?: string;
  masterPlaylistName?: string;
  segmentDurationSeconds?: number;
  playlistSize?: number;
  hashIntervalMs?: number;
}

/** Lifecycle and hash-generation contract used by the origin server. */
export interface StreamController {
  readonly playlistPath: string;
  readonly qualities: string[];
  isRunning(): boolean;
  start(): Promise<void>;
  stop(): Promise<void>;
  ensureHash(segmentName: string): Promise<string>;
}

const isMissing = (error: unknown): boolean =>
  error instanceof Error && "code" in error && error.code === "ENOENT";

/** Generates adaptive HLS output and SHA-256 sidecar files with FFmpeg. */
export class HlsStreamer implements StreamController {
  readonly playlistPath: string;
  readonly qualities: string[];
  private readonly ffmpegPath: string;
  private readonly segmentDurationSeconds: number;
  private readonly playlistSize: number;
  private readonly hashIntervalMs: number;
  private child: ChildProcess | undefined;
  private hashTimer: NodeJS.Timeout | undefined;
  private hashGeneration: Promise<void> | undefined;
  private startPromise: Promise<void> | undefined;
  private stopPromise: Promise<void> | undefined;
  private readonly pendingHashes = new Map<string, Promise<string>>();

  constructor(private readonly options: StreamerOptions) {
    const masterPlaylistName = options.masterPlaylistName ?? "stream.m3u8";
    this.playlistPath = path.join(options.outputDirectory, masterPlaylistName);
    this.qualities = QUALITY_LEVELS.map((q) => q.name);
    this.ffmpegPath = options.ffmpegPath ?? "ffmpeg";
    this.segmentDurationSeconds =
      options.segmentDurationSeconds ?? DEFAULT_SEGMENT_DURATION_SECONDS;
    this.playlistSize = options.playlistSize ?? DEFAULT_PLAYLIST_SIZE;
    this.hashIntervalMs = options.hashIntervalMs ?? DEFAULT_HASH_INTERVAL_MS;
  }

  isRunning(): boolean {
    return this.child !== undefined && this.child.exitCode === null;
  }

  async start(): Promise<void> {
    if (this.stopPromise) await this.stopPromise;
    if (this.isRunning()) return;
    this.startPromise ??= this.startOnce().finally(() => {
      this.startPromise = undefined;
    });
    return this.startPromise;
  }

  private async startOnce(): Promise<void> {
    await mkdir(this.options.outputDirectory, { recursive: true });
    await this.createVariantDirectories();
    await this.removeOldStreamFiles();

    const child = spawn(this.ffmpegPath, this.ffmpegArguments(), {
      stdio: ["ignore", "ignore", "pipe"],
      cwd: this.options.outputDirectory,
    });
    this.child = child;
    child.stderr?.setEncoding("utf8");
    child.stderr?.on("data", (chunk: string) => {
      for (const line of chunk.trimEnd().split("\n")) {
        if (line) logger.error("ffmpeg_stderr", line);
      }
    });
    child.once("exit", (code, signal) => {
      if (this.child === child) this.child = undefined;
      if (code !== 0 && signal !== "SIGTERM") {
        logger.error(
          "ffmpeg_exited_unexpectedly",
          new Error("FFmpeg exited before shutdown"),
          { code, signal },
        );
      }
    });

    await new Promise<void>((resolve, reject) => {
      const onSpawn = (): void => {
        child.off("error", onError);
        resolve();
      };
      const onError = (error: Error): void => {
        child.off("spawn", onSpawn);
        if (this.child === child) this.child = undefined;
        reject(error);
      };
      child.once("spawn", onSpawn);
      child.once("error", onError);
    });

    this.hashTimer = setInterval(
      () => this.scheduleHashGeneration(),
      this.hashIntervalMs,
    );
    this.hashTimer.unref();
  }

  async stop(): Promise<void> {
    this.stopPromise ??= this.stopOnce().finally(() => {
      this.stopPromise = undefined;
    });
    return this.stopPromise;
  }

  private async stopOnce(): Promise<void> {
    await this.startPromise;
    if (this.hashTimer) {
      clearInterval(this.hashTimer);
      this.hashTimer = undefined;
    }
    const hashGeneration = this.hashGeneration;
    const child = this.child;
    if (child && child.exitCode === null) {
      const exited = new Promise<void>((resolve) =>
        child.once("exit", () => resolve()),
      );
      child.kill("SIGTERM");
      let timeoutTimer: NodeJS.Timeout | undefined;
      try {
        const timeout = new Promise<"timeout">((resolve) => {
          timeoutTimer = setTimeout(() => resolve("timeout"), STOP_TIMEOUT_MS);
          timeoutTimer.unref();
        });
        if ((await Promise.race([exited, timeout])) === "timeout") {
          child.kill("SIGKILL");
          await exited;
        }
      } finally {
        if (timeoutTimer) clearTimeout(timeoutTimer);
      }
    }
    await hashGeneration;
  }

  async ensureHash(segmentName: string): Promise<string> {
    if (!/^[-A-Za-z0-9_./]+\.ts$/.test(segmentName)) {
      throw new Error("Invalid segment name");
    }
    const outputDirectory = path.resolve(this.options.outputDirectory);
    const segmentPath = path.resolve(outputDirectory, segmentName);
    if (!segmentPath.startsWith(`${outputDirectory}${path.sep}`)) {
      throw new Error("Invalid segment name");
    }
    const pending = this.pendingHashes.get(segmentName);
    if (pending) return pending;
    const promise = this.createHashFile(segmentName, segmentPath).finally(() => {
      if (this.pendingHashes.get(segmentName) === promise) {
        this.pendingHashes.delete(segmentName);
      }
    });
    this.pendingHashes.set(segmentName, promise);
    return promise;
  }

  private async createHashFile(
    segmentName: string,
    segmentPath: string,
  ): Promise<string> {
    const hashPath = `${segmentPath}.sha256`;
    try {
      await access(hashPath);
      return hashPath;
    } catch (error) {
      if (!isMissing(error)) throw error;
    }

    const segment = await readFile(segmentPath);
    const digest = createHash("sha256").update(segment).digest("hex");
    const temporaryPath = `${hashPath}.${process.pid}.tmp`;
    await writeFile(temporaryPath, `${digest}  ${segmentName}\n`, "utf8");
    await rename(temporaryPath, hashPath);
    return hashPath;
  }

  private scheduleHashGeneration(): void {
    if (this.hashGeneration) return;
    const generation = this.generatePublishedHashes()
      .catch((error: unknown) => {
        logger.error("segment_hash_generation_failed", error);
      })
      .finally(() => {
        if (this.hashGeneration === generation) this.hashGeneration = undefined;
      });
    this.hashGeneration = generation;
  }

  private ffmpegArguments(): string[] {
    const keyframeInterval = Math.max(
      1,
      Math.round(this.segmentDurationSeconds * TEST_PATTERN_FRAME_RATE),
    );

    const videoScales = QUALITY_LEVELS.map(
      (quality, index) =>
        `[v${index}]scale=${quality.width}:${quality.height}[v${index}out]`,
    );
    const filterChains = [
      `[0:v]split=${QUALITY_LEVELS.length}${QUALITY_LEVELS.map((_, index) => `[v${index}]`).join("")}`,
      ...videoScales,
      `[1:a]asplit=${QUALITY_LEVELS.length}${QUALITY_LEVELS.map((_, index) => `[a${index}]`).join("")}`,
    ];
    const filterComplex = filterChains.join(";");

    const mapArgs: string[] = [];
    const perStreamArgs: string[] = [];
    for (const [index, quality] of QUALITY_LEVELS.entries()) {
      mapArgs.push("-map", `[v${index}out]`);
      mapArgs.push("-map", `[a${index}]`);
      perStreamArgs.push(
        "-b:v",
        quality.videoBitrate,
        "-maxrate",
        quality.maxrate,
        "-bufsize",
        quality.bufsize,
      );
      perStreamArgs.push("-b:a", quality.audioBitrate);
    }

    const varStreamMap = QUALITY_LEVELS.map(
      (quality, index) => `v:${index},a:${index},name:${quality.name}`,
    ).join(" ");

    return [
      "-hide_banner",
      "-loglevel",
      "warning",
      "-re",
      "-f",
      "lavfi",
      "-i",
      `testsrc2=size=1280x720:rate=${TEST_PATTERN_FRAME_RATE}`,
      "-re",
      "-f",
      "lavfi",
      "-i",
      `sine=frequency=${TEST_AUDIO_FREQUENCY_HZ}:sample_rate=${AUDIO_SAMPLE_RATE_HZ}`,
      "-filter_complex",
      filterComplex,
      ...mapArgs,
      "-c:v",
      "libx264",
      "-preset",
      "veryfast",
      "-tune",
      "zerolatency",
      "-pix_fmt",
      "yuv420p",
      ...perStreamArgs,
      "-c:a",
      "aac",
      "-ac",
      String(HLS_DELETE_THRESHOLD),
      "-g",
      String(keyframeInterval),
      "-keyint_min",
      String(keyframeInterval),
      "-sc_threshold",
      "0",
      "-f",
      "hls",
      "-hls_time",
      String(this.segmentDurationSeconds),
      "-hls_list_size",
      String(this.playlistSize),
      "-hls_flags",
      "delete_segments+independent_segments+omit_endlist+program_date_time",
      "-var_stream_map",
      varStreamMap,
      "-master_pl_name",
      path.basename(this.playlistPath),
      "-hls_segment_filename",
      "%v/segment_%06d.ts",
      "%v/stream.m3u8",
    ];
  }

  private async createVariantDirectories(): Promise<void> {
    await Promise.all(
      QUALITY_LEVELS.map((q) =>
        mkdir(path.join(this.options.outputDirectory, q.name), {
          recursive: true,
        }),
      ),
    );
  }

  private async generatePublishedHashes(): Promise<void> {
    // Hash segments from all quality variant playlists
    await Promise.all(
      QUALITY_LEVELS.map(async (q) => {
        const variantPlaylist = path.join(
          this.options.outputDirectory,
          q.name,
          "stream.m3u8",
        );
        let playlist: string;
        try {
          playlist = await readFile(variantPlaylist, "utf8");
        } catch (error) {
          if (isMissing(error)) return;
          throw error;
        }
        const segmentNames = playlist
          .split("\n")
          .map((line) => line.trim())
          .filter(
            (line) => line !== "" && !line.startsWith("#") && line.endsWith(".ts"),
          );
        await Promise.all(
          segmentNames.map(async (segmentName) => {
            try {
              await this.ensureHash(path.join(q.name, segmentName));
            } catch (error) {
              if (!isMissing(error)) throw error;
            }
          }),
        );
      }),
    );
  }

  private async removeOldStreamFiles(): Promise<void> {
    const entries = await readdir(this.options.outputDirectory);
    await Promise.all(
      entries
        .filter(
          (entry) =>
            entry.endsWith(".m3u8") ||
            entry.endsWith(".ts") ||
            entry.endsWith(".ts.sha256") ||
            entry.endsWith(".tmp"),
        )
        .map((entry) =>
          rm(path.join(this.options.outputDirectory, entry), { force: true, recursive: true }),
        ),
    );
    await Promise.all(
      QUALITY_LEVELS.map(async (q) => {
        const variantDir = path.join(this.options.outputDirectory, q.name);
        try {
          const variantEntries = await readdir(variantDir);
          await Promise.all(
            variantEntries.map((entry) =>
              rm(path.join(variantDir, entry), { force: true, recursive: true }),
            ),
          );
        } catch (error) {
          if (!isMissing(error)) throw error;
        }
      }),
    );
  }
}
