apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstreamgrid.trackerName" . }}
  labels:
    {{- include "openstreamgrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: tracker
spec:
  type: ClusterIP
  selector:
    {{- include "openstreamgrid.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tracker
  ports:
    - name: http
      port: {{ .Values.tracker.port }}
      targetPort: http
      protocol: TCP
